### ISSUE TITLE
Guidance Needed: Running easyPheno with PLINK Data Instead of CSV

### ISSUE THREAD

**Issue by jeong2624** [grimmlab/easyPheno#214]
I'm presently utilizing the tutorial data to run easyPheno within a Jupyter notebook, and the tutorial seems to rely on CSV files. However, my available data includes only PLINK and Phenotype data. 
Can you please provide guidance on the steps required to run easyPheno using PLINK data?

**Comment by fhaselbeck** [comment]
Dear jeong2624,
Sorry for the late reply due to holidays.
As described in our data guide (https://easypheno.readthedocs.io/en/latest/data.html), easyPheno also supports PLINK  and .pheno files (if this is the format for your phenotype data). You just need to make sure that all plink files (e.g., '.bed', '.bim', '.fam' OR .map and .ped) and the phenotype file are within the data directory you specify. Then, you just need to define one of the plink files as the genotype_matrix including the data type suffix, so e.g. "genotype_matrix = 'test.bed'", and the same applies for the phenotype file.
